version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 8000:8000
    # networks:
    #   - app_network
  cms:
    container_name: cms
    build:
      context: .
      dockerfile: ./apps/cms/Dockerfile
    restart: unless-stopped
    ports:
      - 1337:1337
    # networks:
    #   - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   app_network:
#     external: true
