name: Build and deploy a container to an Azure Web App DEV CMS

on:
  workflow_dispatch # (manual trigger works on default branch only otherwise it does not do anything. you can not trigger this workflow)
  #[push, pull_request] # use this if you want new change after pushing to github

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Azure container registry
        uses: docker/login-action@v3
        with:
          registry: virittamo.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push container image to registry
        id: build-to-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: virittamo.azurecr.io/${{ secrets.ACR_USERNAME }}/${{secrets.AZURE_WEBAPP_CMS_NAME}}:${{ github.sha }}
          file: ./apps/cms/Dockerfile
          context: ./apps/cms

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_CMS_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_CMS_PUBLISH_PROFILE }}
          images: virittamo.azurecr.io/${{ secrets.ACR_USERNAME }}/${{ secrets.AZURE_WEBAPP_CMS_NAME }}:${{ github.sha }}
