name: Build and deploy a container to an Azure Web App DEV WEB

env:
  AZURE_WEBAPP_NAME: virittamotest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: virittamo.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: virittamo.azurecr.io/${{ secrets.ACR_USERNAME }}/${{env.AZURE_WEBAPP_NAME}}:${{ github.sha }}
          file: ./apps/web/Dockerfile
          context: ./apps/web

  deploy-web:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_WEB_PUBLISH_PROFILE }}
          images: virittamo.azurecr.io/${{ secrets.ACR_USERNAME }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
