name: Deploy CMS

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install Dependencies
        run: cd apps/cms && npm ci
      - name: Run typecheck
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: npm run build
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: https://virittamo.azurecr.io/
      #     username: ${{ secrets.AzureAppService_ContainerUsername_49abf5e34a6d4975914435a0fdf397a2 }}
      #     password: ${{ secrets.AzureAppService_ContainerPassword_1bdbc1ae6c9a47249c618e3506d6294f }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - run: |
      #     docker build . --push --tag virittamo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_49abf5e34a6d4975914435a0fdf397a2 }}/virittamodev:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: virittamocmstest
          slot-name: development
          publish-profile: ${{ secrets.AZURE_CMS_PUBLISH_PROFILE }}
          package: cms
