name: Production deployment to Azure Web App

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: https://virittamo.azurecr.io/
      #     username: ${{ secrets.AzureAppService_ContainerUsername_49abf5e34a6d4975914435a0fdf397a2 }}
      #     password: ${{ secrets.AzureAppService_ContainerPassword_1bdbc1ae6c9a47249c618e3506d6294f }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - run: |
      #     docker build . --push --tag virittamo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_49abf5e34a6d4975914435a0fdf397a2 }}/virittamodev:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # environment:
    #   name: production
    #   url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Deploy to Azure Web App
    #     id: deploy-to-webapp
    #     uses: azure/webapps-deploy@v2
    #     with:
    #       app-name: virittamotest
    #       slot-name: production
    #       publish-profile: ${{ secrets.AzureAppService_PublishProfile_4c0513b5c75f46e8a4be8576f6c1686b }}
    #       images: virittamo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_49abf5e34a6d4975914435a0fdf397a2 }}/virittamodev:${{ github.sha }}
