name: Run tests only

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
      -"main"

jobs:
  
  Tests:
    runs-on: 'ubuntu-latest'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
    - name: Install Dependencies
      run: |
        npm ci
        npm run prepare
    - name: Run Tests
      run: npm test
